/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.RepresentativeRole;

import Business.Asset.Asset;
import Business.Asset.AssetDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BrokerRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nemod
 */
public class AssignPropety extends javax.swing.JPanel {

    /**
     * Creates new form AssignPropety
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private BrokerRequest brokerRequest;
    private Enterprise enterprise;
    private UserAccount useraccount;
    private AssetDirectory assetDirectory;
    private EcoSystem system;
    
    public AssignPropety(JPanel userProcessContainer, UserAccount useraccount, EcoSystem system, BrokerRequest brokerRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.useraccount = useraccount;
        this.brokerRequest = brokerRequest;
        this.system = system;
        this.assetDirectory = (system.getAssetDirectory()== null) ? new AssetDirectory() : system.getAssetDirectory();
        populateTable();
    }
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) housingtable.getModel();
        dtm.setRowCount(0);
        for (Asset asset : assetDirectory.getAssetList()) {
            Object[] row = new Object[12];
            row[0] = asset.getAssetID();
            row[1] = asset.getAssetName();
            row[2] = asset.getAddress();
            row[3] = asset.getCity();
            row[4] = asset.getState();
            row[5] = asset.getZip();
            row[6] = asset.getBedroom();
            row[7] = asset.getBaths();
            row[8] = asset.getCost();
            row[9] = asset.getAvail();
            row[10] = asset.getCustomer();
            row[11] = asset.getMerchant().getName();
            dtm.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        housingtable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblicon = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        btnprevious = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblavailhouses = new javax.swing.JLabel();
        btnsendhousingoptions = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(44, 68, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 660, 70));

        housingtable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        housingtable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        housingtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "House_ID", " Name", "Street_Name", "City", "State", "Zipcode", "No of Bhk", "Restrooms", "Price", "Status", "Customer ", "Ownedby"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(housingtable);
        if (housingtable.getColumnModel().getColumnCount() > 0) {
            housingtable.getColumnModel().getColumn(11).setHeaderValue("Ownedby");
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 830, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeicon.png"))); // NOI18N

        lbltitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbltitle.setText("HOUSE RENTALS");

        btnprevious.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnprevious.setForeground(new java.awt.Color(41, 50, 80));
        btnprevious.setText("BACK");
        btnprevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 632, Short.MAX_VALUE)
                .addComponent(btnprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnprevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbltitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 70));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        lblavailhouses.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblavailhouses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblavailhouses.setText("AVAILABLE HOUSES");
        lblavailhouses.setBorder(new javax.swing.border.MatteBorder(null));

        btnsendhousingoptions.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsendhousingoptions.setText("VIEW HOUSING OPTIONS");
        btnsendhousingoptions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnsendhousingoptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsendhousingoptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendhousingoptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(btnsendhousingoptions, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblavailhouses, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblavailhouses)
                .addGap(45, 45, 45)
                .addComponent(btnsendhousingoptions, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1240, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1241, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void btnsendhousingoptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendhousingoptionsActionPerformed
        // TODO add your handling code here
       ArrayList<String> assetList = new ArrayList<String>();
        if (housingtable.getSelectedRow() >= 0) {
            for (int i = 0; i < housingtable.getSelectedRows().length; i++) {
                String assetID = (String) housingtable.getValueAt(housingtable.getSelectedRows()[i], 0);
                Asset asset = system.getAssetDirectory().fetchAsset(assetID);
                if (!asset.getAvail().equalsIgnoreCase("sold")) {
                    assetList.add(assetID);
                    brokerRequest.setAssetList(assetList);
                    JOptionPane.showMessageDialog(this, "Asset Suggested Successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, asset.getAssetName()+ " is sold! Please suggest other vacant asset.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a house to suggest");
        }
       
    }//GEN-LAST:event_btnsendhousingoptionsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnprevious;
    private javax.swing.JButton btnsendhousingoptions;
    private javax.swing.JTable housingtable;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblavailhouses;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lbltitle;
    // End of variables declaration//GEN-END:variables
}
