/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MerchantRole;

/**
 *
 * @author nemod
 */
public class MerchantWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form MerchantWorkAreaPanel
     */
    public MerchantWorkAreaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        systemAdminPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        managepostupdatesPanel = new javax.swing.JPanel();
        managepostupdates = new javax.swing.JLabel();
        manageprofPanel = new javax.swing.JPanel();
        manageprof = new javax.swing.JLabel();
        managehousingPanel = new javax.swing.JPanel();
        managehouse = new javax.swing.JLabel();
        lblmerchant = new javax.swing.JLabel();
        rightSystemAdminPanel = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 840));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 840));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managepostupdatesPanel.setBackground(new java.awt.Color(255, 255, 255));
        managepostupdatesPanel.setToolTipText("");
        managepostupdatesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managepostupdatesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managepostupdatesPanelMousePressed(evt);
            }
        });

        managepostupdates.setBackground(new java.awt.Color(255, 255, 255));
        managepostupdates.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        managepostupdates.setText("CREATE POST UPDATES");
        managepostupdates.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managepostupdates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managepostupdatesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout managepostupdatesPanelLayout = new javax.swing.GroupLayout(managepostupdatesPanel);
        managepostupdatesPanel.setLayout(managepostupdatesPanelLayout);
        managepostupdatesPanelLayout.setHorizontalGroup(
            managepostupdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managepostupdatesPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(managepostupdates, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        managepostupdatesPanelLayout.setVerticalGroup(
            managepostupdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managepostupdatesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managepostupdates, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(managepostupdatesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 50));

        manageprofPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageprofPanel.setToolTipText("");
        manageprofPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageprofPanel.setPreferredSize(new java.awt.Dimension(264, 48));
        manageprofPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageprofPanelMousePressed(evt);
            }
        });

        manageprof.setBackground(new java.awt.Color(255, 255, 255));
        manageprof.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageprof.setText("MANAGE PROFILE");
        manageprof.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageprof.setPreferredSize(new java.awt.Dimension(115, 16));

        javax.swing.GroupLayout manageprofPanelLayout = new javax.swing.GroupLayout(manageprofPanel);
        manageprofPanel.setLayout(manageprofPanelLayout);
        manageprofPanelLayout.setHorizontalGroup(
            manageprofPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageprofPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(manageprof, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageprofPanelLayout.setVerticalGroup(
            manageprofPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageprofPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageprof, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(manageprofPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 40));

        managehousingPanel.setBackground(new java.awt.Color(255, 255, 255));
        managehousingPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managehousingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managehousingPanelMousePressed(evt);
            }
        });

        managehouse.setBackground(new java.awt.Color(255, 255, 255));
        managehouse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        managehouse.setText("MANAGE PROPERTIES");
        managehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managehouse.setPreferredSize(new java.awt.Dimension(115, 16));
        managehouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managehouseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout managehousingPanelLayout = new javax.swing.GroupLayout(managehousingPanel);
        managehousingPanel.setLayout(managehousingPanelLayout);
        managehousingPanelLayout.setHorizontalGroup(
            managehousingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managehousingPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(managehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        managehousingPanelLayout.setVerticalGroup(
            managehousingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managehouse, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(managehousingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 50));

        lblmerchant.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblmerchant.setText("MERCHANT PANEL");
        lblmerchant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(lblmerchant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        rightSystemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        rightSystemAdminPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        rightSystemAdminPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(systemAdminPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1338, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managepostupdatesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managepostupdatesMousePressed
       
    }//GEN-LAST:event_managepostupdatesMousePressed

    private void managepostupdatesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managepostupdatesPanelMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_managepostupdatesPanelMousePressed

    private void manageprofPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageprofPanelMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_manageprofPanelMousePressed

    private void managehouseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managehouseMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_managehouseMousePressed

    private void managehousingPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managehousingPanelMousePressed
        
    }//GEN-LAST:event_managehousingPanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblmerchant;
    private javax.swing.JLabel managehouse;
    private javax.swing.JPanel managehousingPanel;
    private javax.swing.JLabel managepostupdates;
    private javax.swing.JPanel managepostupdatesPanel;
    private javax.swing.JLabel manageprof;
    private javax.swing.JPanel manageprofPanel;
    private javax.swing.JPanel rightSystemAdminPanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables
}
