/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MerchantRole;

import Business.Asset.Asset;
import Business.Asset.AssetDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nemod
 */
public class PostUpdatesPanel extends javax.swing.JPanel {

    /**
     * Creates new form PostUpdatesPanel
     */
    JFileChooser imgChooser;
    private final EcoSystem system;
    private final UserAccount userAccount;
    BufferedImage img;
    private final JPanel userProcessContainer;
    private final Enterprise enterprise;
    private final AssetDirectory assetDirectory;
    private String imagePath;
    
    public PostUpdatesPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount useraccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = useraccount;
        this.system = system;
        this.assetDirectory = (system.getAssetDirectory()== null) ? new AssetDirectory() : system.getAssetDirectory();
        disableLabels();
    }
    
    public void disableLabels() {
        lblnameinvalid.setVisible(false);
        lblbhkinvalid.setVisible(false);
        lblimageinvalid.setVisible(false);
        lblpriceinvalid.setVisible(false);
        lblrestroominvalid.setVisible(false);
        lbllatinvalid.setVisible(false);
        lblloginvalid.setVisible(false);
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(homeimg.getWidth(), homeimg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    public void displayImage(String imgPath) {
        homeimg.setIcon(ResizeImage(imgPath));
    }
    
    public void emptyAllFields() {
        getname.setText("");
        getaddress.setText("");
        getcity.setText("");
        getstatename.setText("");
        getpincode.setText("");
        homeimg.setText("");
        getprice.setText("");
        getbhk.setText("");
        getrestroomnumber.setText("");
        getlatitude.setText("");
        getlong.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblsubtitle = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        getname = new javax.swing.JTextField();
        lblnameinvalid = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        getaddress = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        getcity = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        getstatename = new javax.swing.JTextField();
        lblzipcode = new javax.swing.JLabel();
        getpincode = new javax.swing.JTextField();
        lblbhk = new javax.swing.JLabel();
        getbhk = new javax.swing.JTextField();
        lblbhkinvalid = new javax.swing.JLabel();
        lblbath = new javax.swing.JLabel();
        getrestroomnumber = new javax.swing.JTextField();
        lblrestroominvalid = new javax.swing.JLabel();
        lblcoordinates = new javax.swing.JLabel();
        getlatitude = new javax.swing.JTextField();
        lbllatinvalid = new javax.swing.JLabel();
        lblcoordinateslon = new javax.swing.JLabel();
        getlong = new javax.swing.JTextField();
        lblloginvalid = new javax.swing.JLabel();
        lblrent = new javax.swing.JLabel();
        getprice = new javax.swing.JTextField();
        lblupload = new javax.swing.JLabel();
        btnchoose = new javax.swing.JButton();
        lblpriceinvalid = new javax.swing.JLabel();
        lblimgpath = new javax.swing.JLabel();
        homeimg = new javax.swing.JLabel();
        lblimageinvalid = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblicon = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        btnprevious = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(241, 241, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(44, 68, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnSave.setText("SUBMIT");
        btnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 105, 60));

        lblsubtitle.setBackground(new java.awt.Color(255, 255, 255));
        lblsubtitle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblsubtitle.setText("HOUSING UPDATES POSTS");
        lblsubtitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblname.setText("Name :");

        getname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblnameinvalid.setBackground(new java.awt.Color(255, 255, 255));
        lblnameinvalid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblnameinvalid.setForeground(new java.awt.Color(255, 0, 0));
        lblnameinvalid.setText("Invalid entry");

        lbladdress.setBackground(new java.awt.Color(255, 255, 255));
        lbladdress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbladdress.setText("Address:");

        getaddress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        getaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getaddressActionPerformed(evt);
            }
        });

        lblcity.setBackground(new java.awt.Color(255, 255, 255));
        lblcity.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblcity.setText("City:");

        getcity.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblstate.setBackground(new java.awt.Color(255, 255, 255));
        lblstate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblstate.setText("State:");

        getstatename.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblzipcode.setBackground(new java.awt.Color(255, 255, 255));
        lblzipcode.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblzipcode.setText("Zipcode:");

        getpincode.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblbhk.setBackground(new java.awt.Color(255, 255, 255));
        lblbhk.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblbhk.setText("No of Bhk:");

        getbhk.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblbhkinvalid.setBackground(new java.awt.Color(255, 255, 255));
        lblbhkinvalid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblbhkinvalid.setForeground(new java.awt.Color(255, 0, 0));
        lblbhkinvalid.setText("Invalid entry");

        lblbath.setBackground(new java.awt.Color(255, 255, 255));
        lblbath.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblbath.setText("No of Restrooms:");

        getrestroomnumber.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblrestroominvalid.setBackground(new java.awt.Color(255, 255, 255));
        lblrestroominvalid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblrestroominvalid.setForeground(new java.awt.Color(255, 0, 0));
        lblrestroominvalid.setText("Invalid enrty");

        lblcoordinates.setBackground(new java.awt.Color(255, 255, 255));
        lblcoordinates.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblcoordinates.setText("Coordinates (LAT)");

        getlatitude.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbllatinvalid.setBackground(new java.awt.Color(255, 255, 255));
        lbllatinvalid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbllatinvalid.setForeground(new java.awt.Color(255, 0, 0));
        lbllatinvalid.setText("Invalid entry please enter latitude in 0.0 format");

        lblcoordinateslon.setBackground(new java.awt.Color(255, 255, 255));
        lblcoordinateslon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblcoordinateslon.setText("Coordinates (LON)");

        getlong.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        getlong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getlongActionPerformed(evt);
            }
        });

        lblloginvalid.setBackground(new java.awt.Color(255, 255, 255));
        lblloginvalid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblloginvalid.setForeground(new java.awt.Color(255, 0, 0));
        lblloginvalid.setText("Invalid entry please enter longitude in 0.0 format");

        lblrent.setBackground(new java.awt.Color(255, 255, 255));
        lblrent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblrent.setText("Cost of Rent:");

        getprice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblupload.setBackground(new java.awt.Color(255, 255, 255));
        lblupload.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblupload.setText("Image Upload:");

        btnchoose.setBackground(new java.awt.Color(255, 255, 255));
        btnchoose.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnchoose.setText("Select Image");
        btnchoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchooseActionPerformed(evt);
            }
        });

        lblpriceinvalid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblpriceinvalid.setForeground(new java.awt.Color(255, 0, 0));
        lblpriceinvalid.setText("Invalid entry please enter  price in 0.0 format");

        lblimgpath.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblimgpath.setForeground(new java.awt.Color(255, 0, 0));

        homeimg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblimageinvalid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblimageinvalid.setForeground(new java.awt.Color(255, 0, 0));
        lblimageinvalid.setText("Upload the image!!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(lblsubtitle))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbladdress)
                                            .addComponent(lblcity)
                                            .addComponent(lblstate)
                                            .addComponent(lblname)
                                            .addComponent(lblzipcode)
                                            .addComponent(lblbhk)
                                            .addComponent(lblbath)
                                            .addComponent(lblcoordinates)
                                            .addComponent(lblcoordinateslon)
                                            .addComponent(lblrent))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(getname, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                            .addComponent(getaddress)
                                            .addComponent(getcity)
                                            .addComponent(getstatename)
                                            .addComponent(getpincode)
                                            .addComponent(getbhk)
                                            .addComponent(getrestroomnumber)
                                            .addComponent(getlatitude)
                                            .addComponent(getlong)
                                            .addComponent(getprice)))
                                    .addComponent(lblupload)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblimgpath, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnchoose, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblimageinvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnameinvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbhkinvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblrestroominvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbllatinvalid)
                            .addComponent(lblloginvalid)
                            .addComponent(lblpriceinvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(homeimg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 239, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblsubtitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(getname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnameinvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladdress)
                    .addComponent(getaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcity)
                    .addComponent(getcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstate)
                    .addComponent(getstatename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblzipcode)
                    .addComponent(getpincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbhk)
                    .addComponent(getbhk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbhkinvalid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbath)
                    .addComponent(getrestroomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrestroominvalid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcoordinates)
                    .addComponent(getlatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllatinvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcoordinateslon)
                    .addComponent(getlong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblloginvalid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblrent)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(getprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblpriceinvalid)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(homeimg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblupload)
                                .addGap(18, 18, 18)
                                .addComponent(lblimgpath, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnchoose, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblimageinvalid)
                        .addGap(24, 24, 24))))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 520));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1280, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeicon.png"))); // NOI18N

        lbltitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbltitle.setText("HOUSE RENTALS");

        btnprevious.setBackground(new java.awt.Color(102, 102, 102));
        btnprevious.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnprevious.setText("BACK");
        btnprevious.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 637, Short.MAX_VALUE)
                .addComponent(btnprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1311, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 26, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getaddressActionPerformed

    private void getlongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getlongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getlongActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
      String name = getname.getText();
        String address = getaddress.getText();
        String city = getcity.getText();
        String state = getstatename.getText();
        String pincode = getpincode.getText();
        Double price = Double.parseDouble((getprice.getText()).isEmpty() ? "0.0" : getprice.getText());
        int bhk = Integer.parseInt((getbhk.getText()).isEmpty() ? "0" : getbhk.getText());
        Double bathroom = Double.parseDouble((getrestroomnumber.getText()).isEmpty() ? "0.0" : getrestroomnumber.getText());
        Double latitude = Double.parseDouble((getlatitude.getText()).isEmpty() ? "0.0" : getlatitude.getText());
        Double longitude = Double.parseDouble((getlong.getText()).isEmpty() ? "0.0" : getlong.getText());
        ImageIcon img = (ImageIcon) homeimg.getIcon();

        if (name.isEmpty() || address.isEmpty() || city.isEmpty() || state.isEmpty() || pincode.isEmpty()
            || getprice.getText().isEmpty() || img == null || getrestroomnumber.getText().isEmpty()
            || getlong.getText().isEmpty() || getlatitude.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all the fields continue!");
        } else if (!system.isDouble(getprice.getText())) {
            lblpriceinvalid.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid rent!");
        } else if (!system.isDouble(getrestroomnumber.getText())) {
            lblrestroominvalid.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid bathroom value!");
        } else if (!system.isDouble(getlong.getText())) {
            lblloginvalid.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid longitude!");
        } else if (!system.isDouble(getlatitude.getText())) {
            lbllatinvalid.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid latitude!");
        } else if (!system.isInt(getbhk.getText())) {
            lblbhkinvalid.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid bhk value!");
        } else if (!system.isInt(getpincode.getText()) || getpincode.getText().length() != 5) {
            JOptionPane.showMessageDialog(null, "Please enter valid 5 digit zipcode!");
        } else {
            disableLabels();
            Asset asset = new Asset();
            asset.setAssetName(name);
            asset.setAddress(address);
            asset.setZip(pincode);
            asset.setCity(city);
            asset.setState(state);
            asset.setBedroom(bhk);
            asset.setBaths(bathroom);
            asset.setPrice(price);
            asset.setStatus("Vacant");
            asset.setHomeImg(imagePath);
            asset.setMerchant(userAccount);
            asset.setAssetID(assetDirectory.createAssetID());
            asset.setLatitude(latitude);
            asset.setLongitude(longitude);
            assetDirectory.addAsset(asset);
            system.setAssetDirectory(assetDirectory);
            JOptionPane.showMessageDialog(null, "Advertisement Added!");
            emptyAllFields();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnchooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchooseActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            String regex
            = "([^\\s]+(\\.(?i)(jpe?g|png|gif|bmp))$)";
            Pattern p = Pattern.compile(regex);
            Matcher m = p.matcher(imagePath);
            if (!m.matches()) {
                JOptionPane.showMessageDialog(null, "Please enter valid image file!");
                return;
            }
            lblimgpath.setText(imagePath);
            displayImage(imagePath);
            JOptionPane.showMessageDialog(null, "Picture Uploaded Successfully");

        }        
    }//GEN-LAST:event_btnchooseActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnpreviousActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnchoose;
    private javax.swing.JButton btnprevious;
    private javax.swing.JTextField getaddress;
    private javax.swing.JTextField getbhk;
    private javax.swing.JTextField getcity;
    private javax.swing.JTextField getlatitude;
    private javax.swing.JTextField getlong;
    private javax.swing.JTextField getname;
    private javax.swing.JTextField getpincode;
    private javax.swing.JTextField getprice;
    private javax.swing.JTextField getrestroomnumber;
    private javax.swing.JTextField getstatename;
    private javax.swing.JLabel homeimg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblbath;
    private javax.swing.JLabel lblbhk;
    private javax.swing.JLabel lblbhkinvalid;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcoordinates;
    private javax.swing.JLabel lblcoordinateslon;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lblimageinvalid;
    private javax.swing.JLabel lblimgpath;
    private javax.swing.JLabel lbllatinvalid;
    private javax.swing.JLabel lblloginvalid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnameinvalid;
    private javax.swing.JLabel lblpriceinvalid;
    private javax.swing.JLabel lblrent;
    private javax.swing.JLabel lblrestroominvalid;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblsubtitle;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblupload;
    private javax.swing.JLabel lblzipcode;
    // End of variables declaration//GEN-END:variables
}
