/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sanik
 */
public class BrokerEnterpriseAdminWorkAreaPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
    Organisation Organisation;

    /**
     * Creates new form BrokerEnterpriseAdminWork
     * @param userProcessContainer
     * @param account
     * @param Organisation
     * @param enterprise
     * @param business
     * @param network
     */
    public BrokerEnterpriseAdminWorkAreaPanel(JPanel userProcessContainer, UserAccount account, Organisation Organisation, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = business;
        this.network = network;
        this.enterprise = enterprise;
        this.Organisation = Organisation;
        manageorganisation();
    }

    private void manageorganisation() {
        BrokerEnterpriseManageOrganizations brokerEnterpriseManageOrganizations = new BrokerEnterpriseManageOrganizations(enterprise.getOrganisationDirectory());
        workPanel.add("BrokerEnterpriseManageOrganizations", brokerEnterpriseManageOrganizations);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);
    }
    private void manageEmployee() {
        BrokerEnterpriseManageEmployees brokerEnterpriseManageEmployees = new BrokerEnterpriseManageEmployees(enterprise.getOrganisationDirectory());
        workPanel.add("BrokerEnterpriseManageEmployees", brokerEnterpriseManageEmployees);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);
    }

    private void manageUsers() {
        BrokerEnterpriseUseraccounts brokerEnterpriseUseraccounts = new BrokerEnterpriseUseraccounts(enterprise, system, Organisation);
        workPanel.add("BrokerEnterpriseUseraccounts", brokerEnterpriseUseraccounts);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);
    }

    private void manageRequests() {
        BrokerEnterpriseWorkRequest brokerEnterpriseWorkRequest = new BrokerEnterpriseWorkRequest(enterprise);
        workPanel.add("BrokerEnterpriseWorkRequest", brokerEnterpriseWorkRequest);
        CardLayout layout = (CardLayout) workPanel.getLayout();
        layout.next(workPanel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        systemAdminPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        manageOrgPanel = new javax.swing.JPanel();
        lblmanageorg = new javax.swing.JLabel();
        lblmanageemp = new javax.swing.JLabel();
        manageEmp = new javax.swing.JPanel();
        manageuserPanel = new javax.swing.JPanel();
        lblmanageuser = new javax.swing.JLabel();
        lblbrokerpage = new javax.swing.JLabel();
        managedemandspanel = new javax.swing.JPanel();
        lblmanagedemands = new javax.swing.JLabel();
        workPanel = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(241, 241, 242));
        jPanel1.setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setMinimumSize(new java.awt.Dimension(280, 840));
        menuPanel.setPreferredSize(new java.awt.Dimension(280, 840));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageOrgPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageOrgPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manageOrgPanel.setToolTipText("");
        manageOrgPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageOrgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageOrgPanelMousePressed(evt);
            }
        });

        lblmanageorg.setBackground(new java.awt.Color(255, 255, 255));
        lblmanageorg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanageorg.setText("MANAGE ORGANIZATION");
        lblmanageorg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmanageorgMousePressed(evt);
            }
        });

        lblmanageemp.setBackground(new java.awt.Color(255, 255, 255));
        lblmanageemp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanageemp.setText("MANAGE EMPLOYEE");
        lblmanageemp.setAutoscrolls(true);
        lblmanageemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmanageempMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageOrgPanelLayout = new javax.swing.GroupLayout(manageOrgPanel);
        manageOrgPanel.setLayout(manageOrgPanelLayout);
        manageOrgPanelLayout.setHorizontalGroup(
            manageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrgPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(manageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmanageorg, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(lblmanageemp, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap())
        );
        manageOrgPanelLayout.setVerticalGroup(
            manageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageOrgPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblmanageorg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmanageemp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPanel.add(manageOrgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 80));

        manageEmp.setBackground(new java.awt.Color(255, 255, 255));
        manageEmp.setToolTipText("");
        manageEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageEmp.setPreferredSize(new java.awt.Dimension(264, 48));
        manageEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageEmpMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageEmpLayout = new javax.swing.GroupLayout(manageEmp);
        manageEmp.setLayout(manageEmpLayout);
        manageEmpLayout.setHorizontalGroup(
            manageEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        manageEmpLayout.setVerticalGroup(
            manageEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        menuPanel.add(manageEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 40));

        manageuserPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageuserPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manageuserPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageuserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageuserPanelMousePressed(evt);
            }
        });

        lblmanageuser.setBackground(new java.awt.Color(255, 255, 255));
        lblmanageuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanageuser.setText("MANAGE USER");
        lblmanageuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmanageuser.setPreferredSize(new java.awt.Dimension(115, 16));

        javax.swing.GroupLayout manageuserPanelLayout = new javax.swing.GroupLayout(manageuserPanel);
        manageuserPanel.setLayout(manageuserPanelLayout);
        manageuserPanelLayout.setHorizontalGroup(
            manageuserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageuserPanelLayout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addComponent(lblmanageuser, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        manageuserPanelLayout.setVerticalGroup(
            manageuserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageuserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmanageuser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.add(manageuserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 280, 40));

        lblbrokerpage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblbrokerpage.setText("BROKER PAGE ");
        lblbrokerpage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPanel.add(lblbrokerpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        managedemandspanel.setBackground(new java.awt.Color(255, 255, 255));
        managedemandspanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        managedemandspanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managedemandspanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managedemandspanelMousePressed(evt);
            }
        });

        lblmanagedemands.setBackground(new java.awt.Color(255, 255, 255));
        lblmanagedemands.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanagedemands.setText("MANAGE DEMANDS");
        lblmanagedemands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmanagedemands.setPreferredSize(new java.awt.Dimension(115, 16));

        javax.swing.GroupLayout managedemandspanelLayout = new javax.swing.GroupLayout(managedemandspanel);
        managedemandspanel.setLayout(managedemandspanelLayout);
        managedemandspanelLayout.setHorizontalGroup(
            managedemandspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managedemandspanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblmanagedemands, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        managedemandspanelLayout.setVerticalGroup(
            managedemandspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmanagedemands, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        menuPanel.add(managedemandspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 280, 40));

        workPanel.setBackground(new java.awt.Color(241, 241, 242));
        workPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        workPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(workPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(systemAdminPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1338, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblmanageorgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmanageorgMousePressed
       manageorganisation();
    }//GEN-LAST:event_lblmanageorgMousePressed

    private void manageOrgPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrgPanelMousePressed
        // TODO add your handling code here:
       manageorganisation();
    }//GEN-LAST:event_manageOrgPanelMousePressed

    private void lblmanageempMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmanageempMousePressed
       manageEmployee();
    }//GEN-LAST:event_lblmanageempMousePressed

    private void manageEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmpMousePressed
        // TODO add your handling code here:
        manageEmployee();
    }//GEN-LAST:event_manageEmpMousePressed

    private void manageuserPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageuserPanelMousePressed
       manageUsers();
    }//GEN-LAST:event_manageuserPanelMousePressed

    private void managedemandspanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managedemandspanelMousePressed
        // TODO add your handling code here:
        manageRequests();
    }//GEN-LAST:event_managedemandspanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblbrokerpage;
    private javax.swing.JLabel lblmanagedemands;
    private javax.swing.JLabel lblmanageemp;
    private javax.swing.JLabel lblmanageorg;
    private javax.swing.JLabel lblmanageuser;
    private javax.swing.JPanel manageEmp;
    private javax.swing.JPanel manageOrgPanel;
    private javax.swing.JPanel managedemandspanel;
    private javax.swing.JPanel manageuserPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel systemAdminPanel;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
