/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MoversNPackers;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import UI.Customer.DisplayJobsInfoPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nemod
 */
public class PackersandMoversWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form PackersandMoversWorkAreaPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
    Organisation organisation;
    public PackersandMoversWorkAreaPanel(JPanel userProcessContainer, UserAccount account, Organisation organisation, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = business;
        this.network = network;
        this.enterprise = enterprise;
        this.organisation = organisation;
        manageJobs();
    }

    private void manageJobs() {
      
        PackersandMoversDetailsPanel packersandMoversDetailsPanel = new PackersandMoversDetailsPanel(UserRight, enterprise, account, system);
        UserRight.add("PackersandMoversDetailsPanel",packersandMoversDetailsPanel);
        CardLayout layout = (CardLayout) UserRight.getLayout();
        layout.next(UserRight);
    }

    private void manageProfile() {
      
        ManagePackersandMoversPanel managePackersandMoversPanel = new ManagePackersandMoversPanel(UserRight, enterprise, account, system);
        UserRight.add("ManagePackersandMoversPanel", managePackersandMoversPanel);
        CardLayout layout = (CardLayout) UserRight.getLayout();
        layout.next(UserRight);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        systemAdminPanel = new javax.swing.JPanel();
        UserLeft = new javax.swing.JPanel();
        manageprofilePanel = new javax.swing.JPanel();
        lblmanageprofile = new javax.swing.JLabel();
        manageoppurtunitiesPanel = new javax.swing.JPanel();
        lblmanageoppurtunities = new javax.swing.JLabel();
        lblpackersandmovers = new javax.swing.JLabel();
        UserRight = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));

        UserLeft.setBackground(new java.awt.Color(255, 255, 255));
        UserLeft.setMinimumSize(new java.awt.Dimension(280, 840));
        UserLeft.setPreferredSize(new java.awt.Dimension(280, 840));
        UserLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageprofilePanel.setBackground(new java.awt.Color(255, 255, 255));
        manageprofilePanel.setToolTipText("");
        manageprofilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageprofilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageprofilePanelMousePressed(evt);
            }
        });

        lblmanageprofile.setBackground(new java.awt.Color(255, 255, 255));
        lblmanageprofile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanageprofile.setText("MANAGE PROFILE");
        lblmanageprofile.setAutoscrolls(true);
        lblmanageprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmanageprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmanageprofileMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageprofilePanelLayout = new javax.swing.GroupLayout(manageprofilePanel);
        manageprofilePanel.setLayout(manageprofilePanelLayout);
        manageprofilePanelLayout.setHorizontalGroup(
            manageprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageprofilePanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblmanageprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        manageprofilePanelLayout.setVerticalGroup(
            manageprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageprofilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmanageprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        UserLeft.add(manageprofilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, -1));

        manageoppurtunitiesPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageoppurtunitiesPanel.setToolTipText("");
        manageoppurtunitiesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageoppurtunitiesPanel.setPreferredSize(new java.awt.Dimension(264, 48));
        manageoppurtunitiesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageoppurtunitiesPanelMousePressed(evt);
            }
        });

        lblmanageoppurtunities.setBackground(new java.awt.Color(255, 255, 255));
        lblmanageoppurtunities.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanageoppurtunities.setText("MANAGE OPPURTUNITIES");
        lblmanageoppurtunities.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmanageoppurtunities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmanageoppurtunitiesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageoppurtunitiesPanelLayout = new javax.swing.GroupLayout(manageoppurtunitiesPanel);
        manageoppurtunitiesPanel.setLayout(manageoppurtunitiesPanelLayout);
        manageoppurtunitiesPanelLayout.setHorizontalGroup(
            manageoppurtunitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageoppurtunitiesPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblmanageoppurtunities, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        manageoppurtunitiesPanelLayout.setVerticalGroup(
            manageoppurtunitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmanageoppurtunities, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        UserLeft.add(manageoppurtunitiesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 40));

        lblpackersandmovers.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblpackersandmovers.setText("PACKERS AND MOVERS");
        lblpackersandmovers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        UserLeft.add(lblpackersandmovers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        UserRight.setBackground(new java.awt.Color(241, 241, 242));
        UserRight.setPreferredSize(new java.awt.Dimension(1058, 840));
        UserRight.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(UserLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(UserRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(UserLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(systemAdminPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1338, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblmanageprofileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmanageprofileMousePressed
        manageProfile();
    }//GEN-LAST:event_lblmanageprofileMousePressed

    private void manageprofilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageprofilePanelMousePressed
        // TODO add your handling code here:
        manageProfile();
    }//GEN-LAST:event_manageprofilePanelMousePressed

    private void lblmanageoppurtunitiesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmanageoppurtunitiesMousePressed
        manageJobs();
    }//GEN-LAST:event_lblmanageoppurtunitiesMousePressed

    private void manageoppurtunitiesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageoppurtunitiesPanelMousePressed
        // TODO add your handling code here:
        manageJobs();
    }//GEN-LAST:event_manageoppurtunitiesPanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserLeft;
    private javax.swing.JPanel UserRight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmanageoppurtunities;
    private javax.swing.JLabel lblmanageprofile;
    private javax.swing.JLabel lblpackersandmovers;
    private javax.swing.JPanel manageoppurtunitiesPanel;
    private javax.swing.JPanel manageprofilePanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables
}
