/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.Asset.AssetDirectory;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sanik
 */
public class DisplayMerchantInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayMerchantInfo
     */
    private JPanel userProcessContainer;
    private UserAccount merchant;
    private AssetDirectory assetDirectory;
    private final EcoSystem system;
    private UserAccount userAccount;
    
    public DisplayMerchantInfoPanel(JPanel userProcessContainer, UserAccount merchant, UserAccount userAccount, EcoSystem system) {
        initComponents();
         this.system = system;
        this.userAccount = userAccount;
        this.merchant = merchant;
        this.userProcessContainer = userProcessContainer;
        populateReqTable();
    }
    
    public void populateReqTable() {
        getname.setText(merchant.getName());
        getcity.setText(merchant.getCity());
        getzip.setText(merchant.getZip());
        getaddress.setText(merchant.getAddress());
        getmail.setText(merchant.getMailId());
        getphone.setText(merchant.getContactnumber());
        getstate.setText(merchant.getState());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblicon = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblzip = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        getzip = new javax.swing.JTextField();
        getaddress = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        getcity = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        getstate = new javax.swing.JTextField();
        lblphone = new javax.swing.JLabel();
        getphone = new javax.swing.JTextField();
        lblmerchant = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        getmail = new javax.swing.JTextField();
        getname = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(44, 68, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbltitle.setText("HOUSE RENTAL SYSTEM");

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 729, Short.MAX_VALUE)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbltitle))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 90));

        jPanel2.setBackground(new java.awt.Color(241, 241, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblzip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblzip.setText("Zipcode");
        jPanel2.add(lblzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        lbladdress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbladdress.setText("Address");
        jPanel2.add(lbladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        getzip.setEnabled(false);
        jPanel2.add(getzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 160, -1));

        getaddress.setEnabled(false);
        jPanel2.add(getaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 160, -1));

        lblcity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblcity.setForeground(new java.awt.Color(0, 0, 51));
        lblcity.setText("City");
        jPanel2.add(lblcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 30, -1));

        getcity.setEnabled(false);
        jPanel2.add(getcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 160, -1));

        lblstate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblstate.setText("State");
        jPanel2.add(lblstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        getstate.setEnabled(false);
        jPanel2.add(getstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 160, -1));

        lblphone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblphone.setText("Phone");
        jPanel2.add(lblphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        getphone.setEnabled(false);
        getphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getphoneActionPerformed(evt);
            }
        });
        jPanel2.add(getphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 160, -1));

        lblmerchant.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblmerchant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmerchant.setText("MERCHANT DETAILS");
        lblmerchant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblmerchant, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, -1));

        lblemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblemail.setText("Mail ID");
        jPanel2.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lblname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblname.setText("Name");
        jPanel2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        getmail.setEnabled(false);
        jPanel2.add(getmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 160, -1));

        getname.setEnabled(false);
        getname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getnameActionPerformed(evt);
            }
        });
        jPanel2.add(getname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void getphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getphoneActionPerformed

    private void getnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JTextField getaddress;
    private javax.swing.JTextField getcity;
    private javax.swing.JTextField getmail;
    private javax.swing.JTextField getname;
    private javax.swing.JTextField getphone;
    private javax.swing.JTextField getstate;
    private javax.swing.JTextField getzip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lblmerchant;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblzip;
    // End of variables declaration//GEN-END:variables
}
