/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.Asset.Asset;
import Business.Asset.AssetDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author sanik
 */
public class DisplayHouseInfoPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AssetDirectory assetDirectory;
    private Asset asset;
    private EcoSystem system;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Network network;
    private Organisation organisation;
    /**
     * Creates new form DisplayHouseInfoPanel
     * @param userProcessContainer
     * @param property
     * @param propertyDirectory
     * @param system
     * @param userAccount
     */
    
    
    public DisplayHouseInfoPanel(JPanel userProcessContainer, Asset asset, AssetDirectory assetDirectory, EcoSystem system, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.asset = asset;
        this.assetDirectory = assetDirectory;
        this.userAccount = userAccount;
        this.system = system;

        populateReqTable();
        
    }
    
    private void populateReqTable() {
//        nameTxt.setText(property.getPropertyName());
//        cityTxt.setText(property.getCity());
//        addressTxt.setText(property.getStreet());
//        pinTxt.setText(property.getPincode());
//        stateTxt.setText(property.getState());
//        priceTxt.setText(Double.toString(property.getPrice()));
//        bhkTxt.setText(Integer.toString(property.getBhk()));
//        bathroomTxt.setText(Double.toString(property.getBathroom()));
//        String imgIcon = property.getUploadImg();
//        imgupload.setIcon(ResizeImage(imgIcon));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblicon = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblzip = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        getzip = new javax.swing.JTextField();
        getaddress = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        getcity = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        getstate = new javax.swing.JTextField();
        lblhouse = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        getname = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        lblpic = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(44, 68, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbltitle.setText("HOUSE RENTAL SYSTEM");

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 729, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbltitle))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 90));

        jPanel2.setBackground(new java.awt.Color(241, 241, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblzip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblzip.setText("Zipcode");
        jPanel2.add(lblzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        lbladdress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbladdress.setText("Address");
        jPanel2.add(lbladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        getzip.setEnabled(false);
        jPanel2.add(getzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 160, -1));

        getaddress.setEnabled(false);
        jPanel2.add(getaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 160, -1));

        lblcity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblcity.setForeground(new java.awt.Color(0, 0, 51));
        lblcity.setText("City");
        jPanel2.add(lblcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 30, -1));

        getcity.setEnabled(false);
        jPanel2.add(getcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 160, -1));

        lblstate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblstate.setText("State");
        jPanel2.add(lblstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        getstate.setEnabled(false);
        jPanel2.add(getstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 160, -1));

        lblhouse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblhouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhouse.setText("HOUSE DETAILS");
        lblhouse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblhouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, -1));

        lblname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblname.setText("Name");
        jPanel2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        getname.setEnabled(false);
        getname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getnameActionPerformed(evt);
            }
        });
        jPanel2.add(getname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, -1));

        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 30, 30));

        lblpic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblpic.setText("Photo");
        jPanel2.add(lblpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));
        jPanel2.add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 270, 190));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void getnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getnameActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnlogout;
    private javax.swing.JTextField getaddress;
    private javax.swing.JTextField getcity;
    private javax.swing.JTextField getname;
    private javax.swing.JTextField getstate;
    private javax.swing.JTextField getzip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblhouse;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblpic;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblzip;
    // End of variables declaration//GEN-END:variables
}
