/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.Asset.AssetDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sanik
 */
public class DisplayJobsInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJobsInfoPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private AssetDirectory assetDirectory;
    private Enterprise enterprise;
    private Network network;
    private Organisation organisation;
    
    public DisplayJobsInfoPanel(JPanel userProcess, UserAccount userAccount, Enterprise enterprise, EcoSystem system, Network network, Organisation organisation) {
        initComponents();
        this.userProcessContainer = userProcess;
        this.system = system;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.assetDirectory = (system.getAssetDirectory()== null) ? new AssetDirectory() : system.getAssetDirectory();
        this.network = network;
        this.organisation = organisation;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lblicon1 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnassetmanagers = new javax.swing.JButton();
        btnmoneylender = new javax.swing.JButton();
        btnphotographer = new javax.swing.JButton();
        btnexaminer = new javax.swing.JButton();
        btnrepairs = new javax.swing.JButton();
        btnmovers = new javax.swing.JButton();
        btnbrokers = new javax.swing.JButton();
        btnconstructor = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(44, 68, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbltitle.setText("HOUSE RENTAL SYSTEM");

        lblicon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeicon.png"))); // NOI18N

        btnBack1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack1.setText("BACK");
        btnBack1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 738, Short.MAX_VALUE)
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbltitle))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblicon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1330, 70));

        jPanel2.setBackground(new java.awt.Color(241, 241, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnassetmanagers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnassetmanagers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-employee-58.png"))); // NOI18N
        btnassetmanagers.setText("SEARCH ASSET MANAGER JOBS");
        btnassetmanagers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnassetmanagers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnassetmanagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnassetmanagersActionPerformed(evt);
            }
        });
        jPanel2.add(btnassetmanagers, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        btnmoneylender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmoneylender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-bank-64 (1).png"))); // NOI18N
        btnmoneylender.setText("SEARCH MONEY LENDER JOBS");
        btnmoneylender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnmoneylender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmoneylender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoneylenderActionPerformed(evt);
            }
        });
        jPanel2.add(btnmoneylender, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 280, 50));

        btnphotographer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnphotographer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-photographer-64.png"))); // NOI18N
        btnphotographer.setText("DISPLAY PHOTOGRAPHER JOBS");
        btnphotographer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnphotographer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnphotographer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphotographerActionPerformed(evt);
            }
        });
        jPanel2.add(btnphotographer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 290, 50));

        btnexaminer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexaminer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-analyse-64.png"))); // NOI18N
        btnexaminer.setText("SEARCH EXAMINER JOBS");
        btnexaminer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnexaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexaminerActionPerformed(evt);
            }
        });
        jPanel2.add(btnexaminer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 330, 50));

        btnrepairs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnrepairs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-maintenance-64.png"))); // NOI18N
        btnrepairs.setText("SEARCH REPAIR SERVICES JOBS");
        btnrepairs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnrepairs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnrepairs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrepairsActionPerformed(evt);
            }
        });
        jPanel2.add(btnrepairs, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 330, 50));

        btnmovers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmovers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-luggage-64.png"))); // NOI18N
        btnmovers.setText("SEARCH MOVERS AND PACKERS JOBS");
        btnmovers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnmovers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmovers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoversActionPerformed(evt);
            }
        });
        jPanel2.add(btnmovers, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 330, 60));

        btnbrokers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbrokers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-broker-48.png"))); // NOI18N
        btnbrokers.setText("SEARCH BROKER JOBS");
        btnbrokers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnbrokers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbrokers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrokersActionPerformed(evt);
            }
        });
        jPanel2.add(btnbrokers, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 330, -1));

        btnconstructor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnconstructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-worker-beard-48.png"))); // NOI18N
        btnconstructor.setText("SEARCH CONSTRUCTOR JOBS");
        btnconstructor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnconstructor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconstructorActionPerformed(evt);
            }
        });
        jPanel2.add(btnconstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 290, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1330, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnassetmanagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnassetmanagersActionPerformed
        ControlManagerJob controlManagerJob = new ControlManagerJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlManagerJob", controlManagerJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnassetmanagersActionPerformed

    private void btnmoneylenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoneylenderActionPerformed
        ControlLoanJob controlLoanJob = new ControlLoanJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlLoanJob", controlLoanJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmoneylenderActionPerformed

    private void btnexaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexaminerActionPerformed
        // TODO add your handling code here:
        ControlExaminerJob controlExaminerJob = new ControlExaminerJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlExaminerJob", controlExaminerJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnexaminerActionPerformed

    private void btnrepairsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrepairsActionPerformed
        ControlRepairServicesJob controlRepairServicesJob = new ControlRepairServicesJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlRepairServicesJob", controlRepairServicesJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnrepairsActionPerformed

    private void btnmoversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoversActionPerformed
        ControlMoversandPackersJob controlMoversandPackersJob = new ControlMoversandPackersJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlMoversandPackersJob", controlMoversandPackersJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmoversActionPerformed

    private void btnbrokersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrokersActionPerformed
        ControlBrokerJob controlBrokerJob = new ControlBrokerJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlBrokerJob", controlBrokerJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnbrokersActionPerformed

    private void btnconstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconstructorActionPerformed
        // TODO add your handling code here:
        ControlConstructorJob controlConstructorJob = new ControlConstructorJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlConstructorJob", controlConstructorJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnconstructorActionPerformed

    private void btnphotographerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphotographerActionPerformed
        // TODO add your handling code here:
        ControlCameraManJob controlPhotographerJob = new ControlCameraManJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlPhotographerJob", controlPhotographerJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnphotographerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnassetmanagers;
    private javax.swing.JButton btnbrokers;
    private javax.swing.JButton btnconstructor;
    private javax.swing.JButton btnexaminer;
    private javax.swing.JButton btnmoneylender;
    private javax.swing.JButton btnmovers;
    private javax.swing.JButton btnphotographer;
    private javax.swing.JButton btnrepairs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblicon1;
    private javax.swing.JLabel lbltitle;
    // End of variables declaration//GEN-END:variables
}
