/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.Asset.AssetDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sanik
 */
public class DisplayJobsInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJobsInfoPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private AssetDirectory assetDirectory;
    private Enterprise enterprise;
    private Network network;
    private Organisation organisation;
    
    public DisplayJobsInfoPanel(JPanel userProcess, UserAccount userAccount, Enterprise enterprise, EcoSystem system, Network network, Organisation organisation) {
        initComponents();
        this.userProcessContainer = userProcess;
        this.system = system;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.assetDirectory = (system.getAssetDirectory()== null) ? new AssetDirectory() : system.getAssetDirectory();
        this.network = network;
        this.organisation = organisation;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblicon = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnBack1 = new javax.swing.JButton();
        btnassetmanagers = new javax.swing.JButton();
        btnmoneylender = new javax.swing.JButton();
        btnphotographer = new javax.swing.JButton();
        btnexaminer = new javax.swing.JButton();
        btnrepairs = new javax.swing.JButton();
        btnmovers = new javax.swing.JButton();
        btnbrokers = new javax.swing.JButton();
        btnconstructor = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(44, 68, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbltitle.setText("HOUSE RENTAL SYSTEM");

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 729, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbltitle))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 90));

        jPanel2.setBackground(new java.awt.Color(241, 241, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 30, 30));

        btnassetmanagers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnassetmanagers.setText("DISPLAY ASSET MANAGER JOBS");
        btnassetmanagers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnassetmanagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnassetmanagersActionPerformed(evt);
            }
        });
        jPanel2.add(btnassetmanagers, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 250, -1));

        btnmoneylender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmoneylender.setText("DISPLAY MONEY LENDER JOBS");
        btnmoneylender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmoneylender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoneylenderActionPerformed(evt);
            }
        });
        jPanel2.add(btnmoneylender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 240, -1));

        btnphotographer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnphotographer.setText("DISPLAY PHOTOGRAPHER JOBS");
        btnphotographer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnphotographer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphotographerActionPerformed(evt);
            }
        });
        jPanel2.add(btnphotographer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 270, -1));

        btnexaminer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexaminer.setText("DISPLAY EXAMINER JOBS");
        btnexaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexaminerActionPerformed(evt);
            }
        });
        jPanel2.add(btnexaminer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 290, -1));

        btnrepairs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnrepairs.setText("DISPLAY REPAIR SERVICES JOBS");
        btnrepairs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnrepairs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrepairsActionPerformed(evt);
            }
        });
        jPanel2.add(btnrepairs, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 290, -1));

        btnmovers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmovers.setText("DISPLAY MOVERS AN PACKERS JOBS");
        btnmovers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmovers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoversActionPerformed(evt);
            }
        });
        jPanel2.add(btnmovers, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 290, -1));

        btnbrokers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbrokers.setText("DISPLAY BROKER JOBS");
        btnbrokers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbrokers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrokersActionPerformed(evt);
            }
        });
        jPanel2.add(btnbrokers, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 290, -1));

        btnconstructor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnconstructor.setText("DISPLAY CONSTRUCTOR JOBS");
        btnconstructor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconstructorActionPerformed(evt);
            }
        });
        jPanel2.add(btnconstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 240, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnassetmanagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnassetmanagersActionPerformed
        ControlManagerJob controlManagerJob = new ControlManagerJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlManagerJob", controlManagerJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnassetmanagersActionPerformed

    private void btnmoneylenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoneylenderActionPerformed
        ControlLoanJob controlLoanJob = new ControlLoanJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlLoanJob", controlLoanJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmoneylenderActionPerformed

    private void btnexaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexaminerActionPerformed
        // TODO add your handling code here:
        ControlExaminerJob controlExaminerJob = new ControlExaminerJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlExaminerJob", controlExaminerJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnexaminerActionPerformed

    private void btnrepairsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrepairsActionPerformed
        ControlRepairServicesJob controlRepairServicesJob = new ControlRepairServicesJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlRepairServicesJob", controlRepairServicesJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnrepairsActionPerformed

    private void btnmoversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoversActionPerformed
        ControlMoversandPackersJob controlMoversandPackersJob = new ControlMoversandPackersJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlMoversandPackersJob", controlMoversandPackersJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmoversActionPerformed

    private void btnbrokersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrokersActionPerformed
        ControlBrokerJob controlBrokerJob = new ControlBrokerJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlBrokerJob", controlBrokerJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnbrokersActionPerformed

    private void btnconstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconstructorActionPerformed
        // TODO add your handling code here:
        ControlConstructorJob controlConstructorJob = new ControlConstructorJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlConstructorJob", controlConstructorJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnconstructorActionPerformed

    private void btnphotographerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphotographerActionPerformed
        // TODO add your handling code here:
        ControlPhotographerJob controlPhotographerJob = new ControlPhotographerJob(userProcessContainer, userAccount, system, enterprise, network, organisation);
        userProcessContainer.add("ControlPhotographerJob", controlPhotographerJob);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnphotographerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnassetmanagers;
    private javax.swing.JButton btnbrokers;
    private javax.swing.JButton btnconstructor;
    private javax.swing.JButton btnexaminer;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmoneylender;
    private javax.swing.JButton btnmovers;
    private javax.swing.JButton btnphotographer;
    private javax.swing.JButton btnrepairs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lbltitle;
    // End of variables declaration//GEN-END:variables
}
