/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sanik
 */
public class MaintenanceProviderAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form MaintenanceProviderWorkArea
     */
     JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount usrAccount;
    Organisation organisation;
    
    public MaintenanceProviderAdminWorkAreaPanel(JPanel userProcessContainer, UserAccount usrAccount, Organisation organisation, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.usrAccount = usrAccount;
        this.system = business;
        this.network = network;
        this.enterprise = enterprise;
        this.organisation = organisation;
        manageOrganisation();
    }

    private void manageOrganisation(){
        
       MaintenanceProviderManageOrganisation maintenanceProviderManageOrganisation = new MaintenanceProviderManageOrganisation(rightSystemAdminPanel, enterprise.getOrganisationDirectory(),enterprise, network, system);
        rightSystemAdminPanel.add("MaintenanceProvider", maintenanceProviderManageOrganisation);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }
    
    private void manageEmployee(){
       
        MaintenanceProviderManageEmployees maintenanceProviderManageEmployees = new MaintenanceProviderManageEmployees(rightSystemAdminPanel, enterprise.getOrganisationDirectory());
        rightSystemAdminPanel.add("MaintenanceProviderManageEmployees", maintenanceProviderManageEmployees);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }
    private void manageUsers(){
        
        MaintenanceProviderEnterpriseUseraccount maintenanceProviderEnterpriseUseraccount = new MaintenanceProviderEnterpriseUseraccount(rightSystemAdminPanel, enterprise, system, organisation);
        rightSystemAdminPanel.add("MaintenanceProviderEnterpriseUseraccount", maintenanceProviderEnterpriseUseraccount);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }
    private void manageDemands(){
       
        MaintenanceProviderEnterpriseWorkRequest maintenanceProviderEnterpriseWorkRequest = new MaintenanceProviderEnterpriseWorkRequest(rightSystemAdminPanel, usrAccount, enterprise, network, system);
        rightSystemAdminPanel.add("MaintenanceProviderEnterpriseWorkRequest", maintenanceProviderEnterpriseWorkRequest);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        systemAdminPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        manageorgPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblmanageorg = new javax.swing.JLabel();
        manageempPanel = new javax.swing.JPanel();
        lblmanageemp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        manageuserPanel = new javax.swing.JPanel();
        lblmanageuser = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maintprovidertitle = new javax.swing.JLabel();
        managedemandsPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblmanagedemands = new javax.swing.JLabel();
        rightSystemAdminPanel = new javax.swing.JPanel();

        jPanel2.setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 840));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 840));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageorgPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageorgPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manageorgPanel.setToolTipText("");
        manageorgPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageorgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageorgPanelMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(215, 81, 81));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-organization-chart-people-48.png"))); // NOI18N

        lblmanageorg.setBackground(new java.awt.Color(255, 255, 255));
        lblmanageorg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanageorg.setText("MANAGE ORGANIZATIONS");
        lblmanageorg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmanageorgMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageorgPanelLayout = new javax.swing.GroupLayout(manageorgPanel);
        manageorgPanel.setLayout(manageorgPanelLayout);
        manageorgPanelLayout.setHorizontalGroup(
            manageorgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageorgPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblmanageorg, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        manageorgPanelLayout.setVerticalGroup(
            manageorgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageorgPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(manageorgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageorgPanelLayout.createSequentialGroup()
                        .addGroup(manageorgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmanageorg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageorgPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );

        jPanel3.add(manageorgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 60));

        manageempPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageempPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manageempPanel.setToolTipText("");
        manageempPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageempPanel.setPreferredSize(new java.awt.Dimension(264, 48));
        manageempPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageempPanelMousePressed(evt);
            }
        });

        lblmanageemp.setBackground(new java.awt.Color(215, 81, 81));
        lblmanageemp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanageemp.setText("MANAGE EMPLOYEE");
        lblmanageemp.setAutoscrolls(true);
        lblmanageemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmanageempMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(215, 81, 81));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-employee-64.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout manageempPanelLayout = new javax.swing.GroupLayout(manageempPanel);
        manageempPanel.setLayout(manageempPanelLayout);
        manageempPanelLayout.setHorizontalGroup(
            manageempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageempPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageempPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblmanageemp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        manageempPanelLayout.setVerticalGroup(
            manageempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageempPanelLayout.createSequentialGroup()
                .addGroup(manageempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmanageemp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel3.add(manageempPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 280, 60));

        manageuserPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageuserPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manageuserPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageuserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageuserPanelMousePressed(evt);
            }
        });

        lblmanageuser.setBackground(new java.awt.Color(215, 81, 81));
        lblmanageuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanageuser.setText("MANAGE USER");
        lblmanageuser.setPreferredSize(new java.awt.Dimension(115, 16));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-account-64.png"))); // NOI18N

        javax.swing.GroupLayout manageuserPanelLayout = new javax.swing.GroupLayout(manageuserPanel);
        manageuserPanel.setLayout(manageuserPanelLayout);
        manageuserPanelLayout.setHorizontalGroup(
            manageuserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageuserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(lblmanageuser, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        manageuserPanelLayout.setVerticalGroup(
            manageuserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageuserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmanageuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(manageuserPanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(manageuserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 280, 60));

        maintprovidertitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        maintprovidertitle.setText("MAINTENANCE PROVIDER ");
        maintprovidertitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(maintprovidertitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 190, -1));

        managedemandsPanel.setBackground(new java.awt.Color(255, 255, 255));
        managedemandsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        managedemandsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managedemandsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managedemandsPanelMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(215, 81, 81));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-give-60.png"))); // NOI18N

        lblmanagedemands.setBackground(new java.awt.Color(215, 81, 81));
        lblmanagedemands.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmanagedemands.setText("MANAGE DEMANDS");
        lblmanagedemands.setPreferredSize(new java.awt.Dimension(115, 16));

        javax.swing.GroupLayout managedemandsPanelLayout = new javax.swing.GroupLayout(managedemandsPanel);
        managedemandsPanel.setLayout(managedemandsPanelLayout);
        managedemandsPanelLayout.setHorizontalGroup(
            managedemandsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managedemandsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmanagedemands, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        managedemandsPanelLayout.setVerticalGroup(
            managedemandsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managedemandsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managedemandsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblmanagedemands, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(managedemandsPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(managedemandsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 70));

        rightSystemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        rightSystemAdminPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        rightSystemAdminPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(systemAdminPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1338, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1338, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblmanageorgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmanageorgMousePressed
        manageOrganisation();
    }//GEN-LAST:event_lblmanageorgMousePressed

    private void manageorgPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageorgPanelMousePressed
        // TODO add your handling code here:
        manageOrganisation();
    }//GEN-LAST:event_manageorgPanelMousePressed

    private void lblmanageempMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmanageempMousePressed
      manageEmployee();
    }//GEN-LAST:event_lblmanageempMousePressed

    private void manageempPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageempPanelMousePressed
        // TODO add your handling code here:
       manageEmployee();
    }//GEN-LAST:event_manageempPanelMousePressed

    private void manageuserPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageuserPanelMousePressed
        manageUsers();
    }//GEN-LAST:event_manageuserPanelMousePressed

    private void managedemandsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managedemandsPanelMousePressed
        // TODO add your handling code here:
         manageDemands();
    }//GEN-LAST:event_managedemandsPanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblmanagedemands;
    private javax.swing.JLabel lblmanageemp;
    private javax.swing.JLabel lblmanageorg;
    private javax.swing.JLabel lblmanageuser;
    private javax.swing.JLabel maintprovidertitle;
    private javax.swing.JPanel managedemandsPanel;
    private javax.swing.JPanel manageempPanel;
    private javax.swing.JPanel manageorgPanel;
    private javax.swing.JPanel manageuserPanel;
    private javax.swing.JPanel rightSystemAdminPanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables
}
