/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CameraManRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Kiran
 */
public class CameraManWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form VideoCamWorkAreaPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
    Organisation organisation;
    public CameraManWorkAreaPanel(JPanel userProcessContainer, UserAccount account, Organisation organisation, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = business;
        this.network = network;
        this.enterprise = enterprise;
        this.organisation = organisation;
        manageOpportunities();
    }
    
     private void manageOpportunities() {
       
        ViewOppurnitiesPanel viewOppurnitiesPanel = new ViewOppurnitiesPanel(UserRight, enterprise, account, system);
        UserRight.add("viewOppurnitiesPanel",viewOppurnitiesPanel);
        CardLayout layout = (CardLayout) UserRight.getLayout();
        layout.next(UserRight);
    }
     
     private void manageProfile() {
       
        ManageCameramanPanel manageCameramanPanel = new ManageCameramanPanel(UserRight, enterprise, account, system);
        UserRight.add("manageCameramanPanel", manageCameramanPanel);
        CardLayout layout = (CardLayout) UserRight.getLayout();
        layout.next(UserRight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        systemAdminPanel = new javax.swing.JPanel();
        UserLeft = new javax.swing.JPanel();
        manageprofilePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblmanageprofile = new javax.swing.JLabel();
        manageoppurtunitesPanel = new javax.swing.JPanel();
        lblmanageoppurtunities = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblsubtitle = new javax.swing.JLabel();
        UserRight = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));

        UserLeft.setBackground(new java.awt.Color(255, 255, 255));
        UserLeft.setMinimumSize(new java.awt.Dimension(280, 840));
        UserLeft.setPreferredSize(new java.awt.Dimension(280, 840));
        UserLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageprofilePanel.setBackground(new java.awt.Color(255, 255, 255));
        manageprofilePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manageprofilePanel.setToolTipText("");
        manageprofilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageprofilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageprofilePanelMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-organization-chart-people-48.png"))); // NOI18N

        lblmanageprofile.setBackground(new java.awt.Color(255, 255, 255));
        lblmanageprofile.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblmanageprofile.setText("MANAGE PROFILE");
        lblmanageprofile.setAutoscrolls(true);
        lblmanageprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmanageprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmanageprofileMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageprofilePanelLayout = new javax.swing.GroupLayout(manageprofilePanel);
        manageprofilePanel.setLayout(manageprofilePanelLayout);
        manageprofilePanelLayout.setHorizontalGroup(
            manageprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageprofilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblmanageprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        manageprofilePanelLayout.setVerticalGroup(
            manageprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(manageprofilePanelLayout.createSequentialGroup()
                .addComponent(lblmanageprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        UserLeft.add(manageprofilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, -1));

        manageoppurtunitesPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageoppurtunitesPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manageoppurtunitesPanel.setToolTipText("");
        manageoppurtunitesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageoppurtunitesPanel.setPreferredSize(new java.awt.Dimension(264, 48));
        manageoppurtunitesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageoppurtunitesPanelMousePressed(evt);
            }
        });

        lblmanageoppurtunities.setBackground(new java.awt.Color(255, 255, 255));
        lblmanageoppurtunities.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblmanageoppurtunities.setText("MANAGE OPPURTUNITIES");
        lblmanageoppurtunities.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmanageoppurtunities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmanageoppurtunitiesMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-online-jobs-application-available-on-a-smartphone-24.png"))); // NOI18N

        javax.swing.GroupLayout manageoppurtunitesPanelLayout = new javax.swing.GroupLayout(manageoppurtunitesPanel);
        manageoppurtunitesPanel.setLayout(manageoppurtunitesPanelLayout);
        manageoppurtunitesPanelLayout.setHorizontalGroup(
            manageoppurtunitesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageoppurtunitesPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmanageoppurtunities)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        manageoppurtunitesPanelLayout.setVerticalGroup(
            manageoppurtunitesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageoppurtunitesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmanageoppurtunities, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        UserLeft.add(manageoppurtunitesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 280, 60));

        lblsubtitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblsubtitle.setText(" CAMERA MAN ");
        lblsubtitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        UserLeft.add(lblsubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        UserRight.setBackground(new java.awt.Color(241, 241, 242));
        UserRight.setPreferredSize(new java.awt.Dimension(1058, 840));
        UserRight.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(UserLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(UserRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(UserLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(systemAdminPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1338, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblmanageprofileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmanageprofileMousePressed
       manageProfile();
    }//GEN-LAST:event_lblmanageprofileMousePressed

    private void manageprofilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageprofilePanelMousePressed
        // TODO add your handling code here:
       manageProfile();
    }//GEN-LAST:event_manageprofilePanelMousePressed

    private void lblmanageoppurtunitiesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmanageoppurtunitiesMousePressed
       manageOpportunities();
    }//GEN-LAST:event_lblmanageoppurtunitiesMousePressed

    private void manageoppurtunitesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageoppurtunitesPanelMousePressed
        // TODO add your handling code here:
        manageOpportunities();
    }//GEN-LAST:event_manageoppurtunitesPanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserLeft;
    private javax.swing.JPanel UserRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmanageoppurtunities;
    private javax.swing.JLabel lblmanageprofile;
    private javax.swing.JLabel lblsubtitle;
    private javax.swing.JPanel manageoppurtunitesPanel;
    private javax.swing.JPanel manageprofilePanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables
}
